# Generated by Django 5.0.9 on 2024-10-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("project_id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("project_manager", models.CharField(max_length=100)),
                ("customer_company", models.CharField(max_length=200)),
            ],
        ),
    ]
